import { env } from "cloudflare:workers";import { requireUser,signOutPath } from "@/lib/auth";import { BarChart3,CalendarPlus,Eye,MousePointerClick,Newspaper,RefreshCw,Users,UserRound } from "lucide-react";import { AdminDataTables,type ActivityRow,type EventSubmissionRow,type LeadRow,type ProfileRow,type SubscriberRow } from "@/components/admin-data-tables";import { ADMIN_EMAIL } from "@/lib/admin-auth";
import { AnalyticsExclusion } from "@/components/analytics-exclusion";
export const dynamic="force-dynamic";
type Row=Record<string,string|number|null>;
async function all(query:string,bindings:(string|number)[]=[]){return (await env.DB.prepare(query).bind(...bindings).all<Row>()).results}
export default async function Admin(){const user=await requireUser("/admin");if(user.email.toLowerCase()!==ADMIN_EMAIL)return <main className="admin-denied"><h1>Acceso restringido</h1><p>Esta área pertenece al administrador de Modo MZA.</p><a href={signOutPath("/admin")} target="_top">Cambiar de cuenta</a></main>;
  const since="-30 days";
  const [totals,topContent,actions,sources,devices,trend,subs,leads,events,subscriberRows,leadRows,eventRows,recentActivity,profileRows]=await Promise.all([
    all("SELECT COUNT(*) views, COUNT(DISTINCT session_id) sessions, COUNT(DISTINCT visitor_id) visitors FROM analytics_events WHERE event_name IN ('page_view','content_view') AND created_at >= datetime('now', ?)",[since]),
    all("SELECT COALESCE(content_slug,path) label, COUNT(*) value FROM analytics_events WHERE event_name IN ('content_view','page_view') AND created_at >= datetime('now', ?) GROUP BY COALESCE(content_slug,path) ORDER BY value DESC LIMIT 8",[since]),
    all("SELECT event_name label, COUNT(*) value FROM analytics_events WHERE created_at >= datetime('now', ?) GROUP BY event_name ORDER BY value DESC",[since]),
    all("SELECT COALESCE(NULLIF(utm_source,''),NULLIF(referrer_host,''),'Directo') label, COUNT(DISTINCT session_id) value FROM analytics_events WHERE created_at >= datetime('now', ?) GROUP BY label ORDER BY value DESC LIMIT 6",[since]),
    all("SELECT COALESCE(device_type,'Sin dato') label, COUNT(DISTINCT session_id) value FROM analytics_events WHERE created_at >= datetime('now', ?) GROUP BY label ORDER BY value DESC",[since]),
    all("SELECT date(created_at) label, COUNT(DISTINCT session_id) value FROM analytics_events WHERE created_at >= datetime('now', '-13 days') GROUP BY date(created_at) ORDER BY label"),
    all("SELECT COUNT(*) value FROM newsletter_subscribers WHERE status='active'"),all("SELECT COUNT(*) value FROM sponsor_leads WHERE status='new'"),all("SELECT COUNT(*) value FROM event_submissions WHERE status='new'"),
    all("SELECT email,status,source,consented_at FROM newsletter_subscribers ORDER BY consented_at DESC LIMIT 500"),
    all("SELECT business,name,email,phone,category,message,status,created_at FROM sponsor_leads ORDER BY created_at DESC LIMIT 500"),
    all("SELECT event_name,organizer,email,phone,event_date,venue,cost,source_url,message,status,created_at FROM event_submissions ORDER BY created_at DESC LIMIT 500"),
    all("SELECT event_name,content_slug,path,value,referrer_host,device_type,created_at FROM analytics_events ORDER BY created_at DESC LIMIT 100"),
    all("SELECT first_name,last_name,email,phone,consented_at,created_at,updated_at FROM user_profiles ORDER BY created_at DESC LIMIT 500")]);
  const t=totals[0]||{};const max=Math.max(1,...trend.map(x=>Number(x.value)));
  return <main className="admin-shell"><header className="admin-top"><div><span className="overline">Privado · Modo MZA</span><h1>Panel de audiencia</h1><p>Últimos 30 días · datos propios, sin cookies publicitarias.</p></div><div className="admin-user"><span>{user.displayName}</span><a href={signOutPath("/admin")} target="_top">Salir</a></div></header>
    <AnalyticsExclusion/>
    <section className="kpi-grid"><Kpi icon={<Eye/>} label="Vistas" value={t.views||0}/><Kpi icon={<Users/>} label="Sesiones" value={t.sessions||0}/><Kpi icon={<RefreshCw/>} label="Visitantes" value={t.visitors||0}/><Kpi icon={<UserRound/>} label="Perfiles" value={profileRows.filter(row=>row.consented_at).length}/><Kpi icon={<MousePointerClick/>} label="Acciones" value={actions.filter(x=>!["page_view","content_view"].includes(String(x.label))).reduce((a,b)=>a+Number(b.value),0)}/><Kpi icon={<Newspaper/>} label="Suscriptores" value={subs[0]?.value||0}/><Kpi icon={<BarChart3/>} label="Leads nuevos" value={leads[0]?.value||0}/><Kpi icon={<CalendarPlus/>} label="Eventos por revisar" value={events[0]?.value||0}/></section>
    <section className="admin-grid"><article className="admin-card wide"><h2>Sesiones · 14 días</h2><div className="mini-chart">{trend.length?trend.map(x=><div key={String(x.label)}><span style={{height:`${Math.max(5,Number(x.value)/max*100)}%`}}/><small>{String(x.label).slice(5)}</small></div>):<p>Los datos aparecerán cuando empiece a entrar audiencia.</p>}</div></article><TableCard title="Contenido más visto" rows={topContent}/><TableCard title="Acciones" rows={actions}/><TableCard title="Origen de visitas" rows={sources}/><TableCard title="Dispositivos" rows={devices}/></section>
    <AdminDataTables profiles={profileRows as ProfileRow[]} subscribers={subscriberRows as SubscriberRow[]} leads={leadRows as LeadRow[]} eventSubmissions={eventRows as EventSubmissionRow[]} activity={recentActivity as ActivityRow[]}/>
    <section className="admin-card"><h2>Qué estamos midiendo</h2><p className="admin-note">Vistas, contenido abierto, búsquedas, filtros, guardados, mapas, compartir, fuentes, newsletter y formularios comerciales. Cada evento guarda ruta, campaña UTM, dispositivo y sesión anónima; no guardamos IP.</p></section>
  </main>}
function Kpi({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <div className="kpi">{icon}<span>{label}</span><b>{Number(value).toLocaleString("es-AR")}</b></div>}
function TableCard({title,rows}:{title:string;rows:Row[]}){const max=Math.max(1,...rows.map(x=>Number(x.value)));return <article className="admin-card"><h2>{title}</h2>{rows.length?rows.map((x,i)=><div className="rank-row" key={`${x.label}-${i}`}><span>{String(x.label).replaceAll("-"," ")}</span><i><em style={{width:`${Number(x.value)/max*100}%`}}/></i><b>{Number(x.value).toLocaleString("es-AR")}</b></div>):<p className="admin-note">Aún sin datos.</p>}</article>}
