"use client";
import { Bookmark,ExternalLink,Navigation,Share2 } from "lucide-react";
import { toast } from "sonner";
import { hrefFor,type ContentItem } from "@/lib/content";
import { track } from "@/lib/track-client";
import { useSaved } from "@/components/saved-provider";
import { directionsUrl } from "@/components/location-map";
const remember=(eventName:string,contentSlug:string)=>fetch("/api/activity",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventName,contentSlug}),keepalive:true}).catch(()=>{});
export function DetailActions({item}:{item:ContentItem}){const {isSaved,toggle,viewer}=useSaved(),saved=isSaved(item.slug);async function share(){track("share",{contentSlug:item.slug,category:item.category,zone:item.zone});if(viewer?.profileComplete)void remember("share",item.slug);try{if(navigator.share){await navigator.share({title:item.title,text:item.summary,url:location.href})}else{await navigator.clipboard.writeText(location.href);toast.success("Link copiado")}}catch(err){if(err instanceof Error&&err.name==="AbortError")return;toast.error("No se pudo compartir el link")}}return <>{item.mapUrl&&<a className="primary-action" href={directionsUrl(item)} target="_blank" rel="noreferrer" onClick={()=>{track("map_click",{contentSlug:item.slug,category:item.category,zone:item.zone,value:"directions"});if(viewer?.profileComplete)void remember("map_click",item.slug)}}><Navigation size={18}/>Cómo llegar</a>}{item.editorial&&<a className="secondary-action" href={item.sourceUrl} target="_blank" rel="noreferrer" onClick={()=>{track("source_click",{contentSlug:item.slug,category:item.category,zone:item.zone});if(viewer?.profileComplete)void remember("source_click",item.slug)}}><ExternalLink size={17}/>Consultar canal oficial</a>}{viewer?<button className="secondary-action" onClick={()=>{void toggle(item.slug);track(saved?"unsave":"save",{contentSlug:item.slug})}}><Bookmark size={17} fill={saved?"currentColor":"none"}/>{saved?"En favoritos":"Guardar favorito"}</button>:<a className="secondary-action" href={`/ingresar?returnTo=${encodeURIComponent(hrefFor(item))}`}><Bookmark size={17}/>Ingresá para guardar</a>}<button className="secondary-action" onClick={share}><Share2 size={17}/>Compartir</button></>}
